growth_bubble:
  parser_type: growth
  plot_type: bubble_interactive
  figure:
    title: Simple Bubble Plot
    toolbar_location: null
  linear_cmap:
    field_name: color
    palette: Viridis256
  color_bar:
    width: 8
    location: [0, 0]
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - individual
      - by_company_size
    single_choice_default: individual

base_line_interactive:
  parser_type: base
  plot_type: line_interactive
  background_fill_color: "#F6F6F6"
  general:
    y_axis_label: Umsatz in Mio. €
    toolbar_location: null
  line:
    legend_label: Line
  legend_title: Legend
  label_text_font_size: 13pt
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - anzahl_unternehmen_insgesamt
      - anzahl_innovative_unternehmen
      - anzahl_innovatoren
      #- umsatz_mio
      - innovations_ausgaben_mio
      - fue_ausgaben_mio
      - umsatz_mio_produkt
      - umsatz_mio_markt
    single_choice_default: anzahl_unternehmen_insgesamt
    multi_choice:
      - nahrung
      - pharma
      - holz
      - metall
      - elektroindustrie
      - fahrzeugbau
      - sonstige_konsumgueter
      - energie
      - telekommunikation
      - software
      - finanz
      - unternehmensberatung
      - architektur
      - forschung
      - kreativ

shares_pie_interactive:
  parser_type: shares
  plot_type: pie_interactive
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - "2012"
      - "2021"
    single_choice_default: "2012"
    single_choice_highlight:
      - Maschinen-/Fahrzeugbau
      - Elektroindustrie/Instrumententechnik
      - Pharma/Chemie/Kunststoff
      - Software/Datenverarbeitung
      - restliche Branchen
    single_choice_highlight_default: Maschinen-/Fahrzeugbau

fue_pie_interactive:
  parser_type: fue
  plot_type: pie_interactive
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - "2011"
      - "2020"
    single_choice_default: "2011"
    single_choice_highlight:
      - Wirtschaft
      - Hochschulen
      - Staat
    single_choice_highlight_default: Wirtschaft

coop_partner_bar_interactive:
  parser_type: coop
  plot_type: bar_interactive
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - "2012"
      - "2020"
    single_choice_default: "2012"
    single_choice_2:
      - insgesamt
      - Hochschulen
      - staatl. Forschung
      - Kunden (privatwirtschaftl.)
      - Lieferanten
      - Wettbewerber
    single_choice_2_default: insgesamt
