growth_bubble:
  parser_type: growth
  plot_type: bubble
  figure:
    title: Simple Bubble Plot
    toolbar_location: null
  linear_cmap:
    field_name: color
    palette: Viridis256
  color_bar:
    width: 8
    location: [0, 0]

base_line_interactive:
  parser_type: base
  plot_type: line_interactive
  general:
    title: Basis Chart
    x_axis_label: X-axis
    y_axis_label: Y-axis
    toolbar_location: null
    y_range: [0, 14]
  line:
    line_width: 2
    legend_label: Line
    line_color: blue
  legend_title: Legend
  label_text_font_size: 12pt
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - anzahl
      - umsatz
    single_choice_default: anzahl
    multi_choice:
      - nahrung
      - pharma
      - textil
    multi_choice_default:
      - nahrung
      - pharma

shares_pie_interactive:
  parser_type: shares
  plot_type: pie_interactive
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - "2012"
      - "2021"
    single_choice_default: "2012"
    single_choice_highlight:
      - Maschinen-/Fahrzeugbau
      - Elektroindustrie/Instrumententechnik
      - Pharma/Chemie/Kunststoff
      - Software/Datenverarbeitung
      - restliche Branchen
    single_choice_highlight_default: Maschinen-/Fahrzeugbau

fue_pie_interactive:
  parser_type: fue
  plot_type: pie_interactive
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - "2011"
      - "2020"
    single_choice_default: "2011"
    single_choice_highlight:
      - Wirtschaft
      - Hochschulen
      - Staat
    single_choice_highlight_default: Wirtschaft

coop_partner:
  parser_type: coop
  plot_type: bar_interactive
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - "2012"
      - "2020"
    single_choice_default: "2012"
    single_choice_2:
      - insgesamt
      - Hochschulen
      - staatl. Forschung
      - Kunden (privatwirtschaftl.)
      - Lieferanten
      - Wettbewerber
    single_choice_2_default: insgesamt

