bar_custom:
  plot_type: bar
  general:
    title: Simple Bar Chart
    x_axis_label: Categories
    y_axis_label: Values
  vbar:
    width: 0.5
    legend_label: Values
    line_color: blue
    fill_color: blue
  legend_title: Legend
  label_text_font_size: 12pt

bubble_custom:
  plot_type: bubble
  figure:
    title: Simple Bubble Plot
    toolbar_location: null
  linear_cmap:
    field_name: color
    palette: Viridis256
  circle:
    legend_field: color
  color_bar:
    width: 8
    location: [0, 0]

line_custom:
  plot_type: line
  general:
    title: Simple Line Chart
    x_axis_label: X-axis
    y_axis_label: Y-axis
  line:
    line_width: 2
    legend_label: Line
    line_color: blue
  legend_title: Legend
  label_text_font_size: 12pt

basis_custom:
  plot_type: line_interactive
  general:
    title: Basis Chart
    x_axis_label: X-axis
    y_axis_label: Y-axis
    toolbar_location: null
    y_range: [0, 14]
  line:
    line_width: 2
    legend_label: Line
    line_color: blue
  legend_title: Legend
  label_text_font_size: 12pt
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - anzahl_unternehmen_insgesamt
      - umsatz_mio
    single_choice_default: anzahl_unternehmen_insgesamt
    multi_choice:
      - nahrung
      - pharma
      - metall
    multi_choice_default:
      - nahrung
      - pharma
      - metall

donut_shares:
  plot_type: pie_interactive
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - "2012"
      - "2021"
    single_choice_default: "2012"
    single_choice_highlight:
      - Maschinen-/Fahrzeugbau
      - Elektroindustrie/Instrumententechnik
      - Pharma/Chemie/Kunststoff
      - Software/Datenverarbeitung
      - restliche Branchen
    single_choice_highlight_default: Maschinen-/Fahrzeugbau

donut_fue:
  plot_type: pie_interactive
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - "2011"
      - "2020"
    single_choice_default: "2011"
    single_choice_highlight:
      - Wirtschaft
      - Hochschulen
      - Staat
    single_choice_highlight_default: Wirtschaft

