mapping_branches = {
    "Nahrung/Getränke/Tabak": "nahrung",
    "Pharma/Chemie/Kunststoff": "pharma",
    "Textil/Chemie/Kunststoff": "pharma",
    "Holz/Papier/Druck": "holz",
    "Metall/Glas/Steinwaren": "metall",
    "Elektroindustrie/Instrumententechnik": "elektroindustrie",
    "Maschinen-/Fahrzeugbau": "fahrzeugbau",
    "sonstige Konsumgüter": "sonstige_konsumgueter",
    "Energie/Wasser/Entsorgung": "energie",
    "Verlage/Film/Rundfunk/Telekommunikation": "telekommunikation",
    "Software/Datenverarbeitung": "software",
    "Finanzdienstleistungen": "finanz",
    "Unternehmensberatung": "unternehmensberatung",
    "Architektur-/Ingenieurbüros/techn. Labore": "architektur",
    "Forschung und Entwicklung": "forschung",
    "Kreativdienstleistungen": "kreativ",
    "Industrie": "industrie",
    "Dienstleistungen": "dienstleistungen",
    "Insgesamt": "insgesamt",
    "beschaeftigte_5_9": "beschaeftigte_5_9",
    "beschaeftigte_10_19": "beschaeftigte_10_19",
    "beschaeftigte_20_49": "beschaeftigte_20_49",
    "beschaeftigte_50_249": "beschaeftigte_50_249",
    "beschaeftigte_250_999": "beschaeftigte_250_999",
    "beschaeftigte_1000": "beschaeftigte_1000",
}

mapping_employees_n = {
    "5-9": "beschaeftigte_5_9",
    "10-19": "beschaeftigte_10_19",
    "20-49": "beschaeftigte_20_49",
    "50-249": "beschaeftigte_50_249",
    "250-999": "beschaeftigte_250_999",
    "1.000 u.m.": "beschaeftigte_1000",
}

mapping_units = {
    "Anzahl der Unternehmen insgesamt": "anzahl_unternehmen_insgesamt",
    "Anzahl der innovations-aktiven Unternehmen": "anzahl_innovative_unternehmen",
    "Anzahl der Innovatoren": "anzahl_innovatoren",
    "Anzahl Beschäftigte": "anzahl_beschaeftigte",
    "Umsatz in Mio. €": "umsatz_mio",
    "Umsatz mit Produktneu-heiten in Mio. €": "umsatz_mio_produkt",
    "Umsatz mit Marktneu-heiten in Mio. €": "umsatz_mio_markt",
    "Innovations-ausgaben in Mio. €": "innovations_ausgaben_mio",
    "FuE-Ausgaben in Mio. €": "fue_ausgaben_mio",
}