growth_bubble_interactive:
  general:
    y_axis_label: Wachstum deutsche FuE-Ausgaben 2018-2021 in %
    x_axis_label: Deutsche Fue-Ausgaben 2021 in Mio. €
  parser_type: growth
  plot_type: bubble_interactive
  tooltip:
    tooltip_cat_1: Wachstum
    tooltip_cat_2: Beschäftigte in D
  linear_cmap:
    field_name: color
  color_bar:
    width: 8
    location: [0, 0]
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - individual
      - by_company_size
  filters_defaults:
    single_choice: individual

base_line_interactive:
  general:
    y_axis_label: Umsatz in Mio. €
  label_text_font_size: 13pt
  parser_type: base
  plot_type: line_interactive
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - anzahl_unternehmen_insgesamt
      - anzahl_innovative_unternehmen
      - anzahl_innovatoren
      #- umsatz_mio
      - innovations_ausgaben_mio
      - fue_ausgaben_mio
      - umsatz_mio_produkt
      - umsatz_mio_markt
    multi_choice:
      - nahrung
      - pharma
      - holz
      - metall
      - elektroindustrie
      - fahrzeugbau
      - sonstige_konsumgueter
      - energie
      - telekommunikation
      - software
      - finanz
      - unternehmensberatung
      - architektur
      - forschung
      - kreativ
  filters_defaults:
    single_choice: anzahl_unternehmen_insgesamt

shares_pie_interactive:
  parser_type: shares
  plot_type: pie_interactive
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - "2012"
      - "2021"
    single_choice_highlight:
      - Maschinen-/Fahrzeugbau
      - Elektroindustrie/Instrumententechnik
      - Pharma/Chemie/Kunststoff
      - Software/Datenverarbeitung
      - restliche Branchen
  filters_defaults:
    single_choice: "2012"
    single_choice_highlight: Maschinen-/Fahrzeugbau

fue_pie_interactive:
  parser_type: fue
  plot_type: pie_interactive
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - "2011"
      - "2020"
    single_choice_highlight:
      - Wirtschaft
      - Hochschulen
      - Staat
  filters_defaults:
    single_choice: "2011"
    single_choice_highlight: Wirtschaft

coop_partner_bar_interactive:
  parser_type: coop
  parser_subtype: partner
  plot_type: bar_interactive
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - "2012"
      - "2020"
    single_choice_2:
      - insgesamt
      - Hochschulen
      - staatl. Forschung
      - Kunden (privatwirtschaftl.)
      - Lieferanten
      - Wettbewerber
  filters_defaults:
    single_choice: "2012"
    single_choice_2: insgesamt

coop_region_bar_interactive:
  parser_type: coop
  parser_subtype: region
  plot_type: bar_interactive
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - "2012"
      - "2020"
    single_choice_2:
      - der Region
      - anderen Regionen in Deutschland
      - anderen europäischen Ländern
      - den USA
      - Asien
      - anderen Ländern
  filters_defaults:
    single_choice: "2012"
    single_choice_2: Asien
