growth_bubble_interactive:
  parser_type: growth
  plot_type: bubble_interactive
  figure:
    title: Simple Bubble Plot
    toolbar_location: null
  linear_cmap:
    field_name: color
    palette: Viridis256
  color_bar:
    width: 8
    location: [0, 0]
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - individual
      - by_company_size
  filters_defaults:
    single_choice: individual

base_line_interactive:
  parser_type: base
  plot_type: line_interactive
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - anzahl_unternehmen_insgesamt
      - anzahl_innovative_unternehmen
      - anzahl_innovatoren
      #- umsatz_mio
      - innovations_ausgaben_mio
      - fue_ausgaben_mio
      - umsatz_mio_produkt
      - umsatz_mio_markt
    multi_choice:
      - nahrung
      - pharma
      - holz
      - metall
      - elektroindustrie
      - fahrzeugbau
      - sonstige_konsumgueter
      - energie
      - telekommunikation
      - software
      - finanz
      - unternehmensberatung
      - architektur
      - forschung
      - kreativ
  filters_defaults:
    single_choice: anzahl_unternehmen_insgesamt

shares_pie_interactive:
  parser_type: shares
  plot_type: pie_interactive
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - "2012"
      - "2021"
    single_choice_highlight:
      - Maschinen-/Fahrzeugbau
      - Elektroindustrie/Instrumententechnik
      - Pharma/Chemie/Kunststoff
      - Software/Datenverarbeitung
      - restliche Branchen
  filters_defaults:
    single_choice: "2012"
    single_choice_highlight: Maschinen-/Fahrzeugbau

fue_pie_interactive:
  parser_type: fue
  plot_type: pie_interactive
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - "2011"
      - "2020"
    single_choice_highlight:
      - Wirtschaft
      - Hochschulen
      - Staat
  filters_defaults:
    single_choice: "2011"
    single_choice_highlight: Wirtschaft

coop_partner_bar_interactive:
  parser_type: coop
  plot_type: bar_interactive
  plot_codes:
    - ber
    - de
  filters:
    single_choice:
      - "2012"
      - "2020"
    single_choice_2:
      - insgesamt
      - Hochschulen
      - staatl. Forschung
      - Kunden (privatwirtschaftl.)
      - Lieferanten
      - Wettbewerber
  filters_defaults:
    single_choice: "2012"
    single_choice_2: insgesamt
