branch_groups = {
    "Nahrung/Getränke/Tabak": "individual",
    "Pharma/Chemie/Kunststoff": "individual",
    "Holz/Papier/Druck": "individual",
    "Metall/Glas/Steinwaren": "individual",
    "Elektroindustrie/Instrumententechnik": "individual",
    "Maschinen-/Fahrzeugbau": "individual",
    "sonstige Konsumgüter": "individual",
    "Energie/Wasser/Entsorgung": "individual",
    "Verlage/Film/Rundfunk/Telekommunikation": "individual",
    "Software/Datenverarbeitung": "individual",
    "Finanzdienstleistungen": "individual",
    "Unternehmensberatung": "individual",
    "Architektur-/Ingenieurbüros/techn. Labore": "individual",
    "Forschung und Entwicklung": "individual",
    "Kreativdienstleistungen": "individual",
    "5-9 Beschäftigte": "by_company_size",
    "10-19 Beschäftigte": "by_company_size",
    "20-49 Beschäftigte": "by_company_size",
    "50-249 Beschäftigte": "by_company_size",
    "250-999 Beschäftigte": "by_company_size",
    "1.000 u.m. Beschäftigte": "by_company_size",
    "Spitzentechnologie": "by_branch_class",
    "Hochwertige Technologie": "by_branch_class",
    "Wissensint. DL - Finanzen": "by_branch_class",
    "Wissensint. DL - Kommunikation": "by_branch_class",
    "Wissensint. DL - technische Beratung": "by_branch_class",
    "Wissensint. DL - nichttechnische Beratung": "by_branch_class",
    "Wissensint. DL - Medien/Kultur": "by_branch_class",
}

mapping_branches = {
    "Nahrung/Getränke/Tabak": "nahrung",
    "Pharma/Chemie/Kunststoff": "pharma",
    "Textil/Chemie/Kunststoff": "pharma",
    "Holz/Papier/Druck": "holz",
    "Metall/Glas/Steinwaren": "metall",
    "Elektroindustrie/Instrumententechnik": "elektroindustrie",
    "Maschinen-/Fahrzeugbau": "fahrzeugbau",
    "sonstige Konsumgüter": "sonstige_konsumgueter",
    "Energie/Wasser/Entsorgung": "energie",
    "Verlage/Film/Rundfunk/Telekommunikation": "telekommunikation",
    "Software/Datenverarbeitung": "software",
    "Finanzdienstleistungen": "finanz",
    "Unternehmensberatung": "unternehmensberatung",
    "Architektur-/Ingenieurbüros/techn. Labore": "architektur",
    "Forschung und Entwicklung": "forschung",
    "Kreativdienstleistungen": "kreativ",
    "Industrie": "industrie",
    "Dienstleistungen": "dienstleistungen",
    "Insgesamt": "insgesamt",
    "beschaeftigte_5_9": "beschaeftigte_5_9",
    "beschaeftigte_10_19": "beschaeftigte_10_19",
    "beschaeftigte_20_49": "beschaeftigte_20_49",
    "beschaeftigte_50_249": "beschaeftigte_50_249",
    "beschaeftigte_250_999": "beschaeftigte_250_999",
    "beschaeftigte_1000": "beschaeftigte_1000",
}

mapping_branch_types = {
    "nahrung": "industrie",
    "pharma": "industrie",
    "holz": "industrie",
    "metall": "industrie",
    "elektroindustrie": "industrie",
    "fahrzeugbau": "industrie",
    "sonstige_konsumgueter": "industrie",
    "energie": "industrie",
    "telekommunikation": "dienstleistungen",
    "software": "industrie",
    "finanz": "industrie",
    "unternehmensberatung": "industrie",
    "architektur": "industrie",
    "forschung": "industrie",
    "kreativ": "industrie",
}

mapping_employees_n = {
    "5-9": "beschaeftigte_5_9",
    "10-19": "beschaeftigte_10_19",
    "20-49": "beschaeftigte_20_49",
    "50-249": "beschaeftigte_50_249",
    "250-999": "beschaeftigte_250_999",
    "1.000 u.m.": "beschaeftigte_1000",
}

mapping_units = {
    "Anzahl der Unternehmen insgesamt": "anzahl_unternehmen_insgesamt",
    "Anzahl der innovations-aktiven Unternehmen": "anzahl_innovative_unternehmen",
    "Anzahl der Innovatoren": "anzahl_innovatoren",
    "Anzahl Beschäftigte": "anzahl_beschaeftigte",
    "Umsatz in Mio. €": "umsatz_mio",
    "Umsatz mit Produktneu-heiten in Mio. €": "umsatz_mio_produkt",
    "Umsatz mit Marktneu-heiten in Mio. €": "umsatz_mio_markt",
    "Innovations-ausgaben in Mio. €": "innovations_ausgaben_mio",
    "FuE-Ausgaben in Mio. €": "fue_ausgaben_mio",
    "Innovations-aktive Unternehmen": "innovations_aktive_unternehmen",
    "Innovatoren": "innovatoren",
    "Produkt-innovatoren": "produkt_innovatoren",
    "Prozess-innovatoren": "prozess_innovatoren",
    "Unternehmen mit Produkt-innovationen im Bereich physischer Waren": "unternehmen_produkt_physisch",
    "Unternehmen mit Produkt-innovationen im Bereich Dienst-leistungen": "unternehmen_produkt_dienstleistung",
    "Unternehmen mit Markt-neuheiten": "unternehmen_markt_neuheiten",
    "Unternehmen mit Prozess-innovationen im Bereich Produktions-verfahren, Verfahren zur Dienst-leistungs-erbringung": "unternehmen_prozess_produktion",
    "Unternehmen mit Prozess-innovationen im Bereich logistische Verfahren": "unternehmen_prozess_logistik",
    "Unternehmen mit Prozess-innovationen im Bereich Informations-verarbeitung": "unternehmen_prozess_informationsverarbeitung",
    "Unternehmen mit Prozess-innovationen im Bereich unterstüt-zende Ver-fahren für Verwaltung/ Adminis-tration": "unternehmen_prozess_verwaltung",
    "Unternehmen mit Prozess-innovationen im Bereich Organisation von Geschäfts-prozessen": "unternehmen_prozess_organisation",
    "Unternehmen mit Prozess-innovationen im Bereich Arbeits-organisation": "unternehmen_prozess_arbeitsorganisation",
    "Unternehmen mit Prozess-innovationen im Bereich Marketing": "unternehmen_prozess_marketing",
    "Unternehmen mit kosten-senkenden Prozess-innovationen": "unternehmen_prozess_kostensenkung",
    "Unternehmen mit kontinuierlicher FuE-Tätigkeit": "unternehmen_fue_kontinuierlich",
    "Unternehmen mit gelegentlicher FuE-Tätigkeit": "unternehmen_fue_gelegentlich",
    "Unternehmen mit Vergabe von FuE-Aufträgen an Dritte": "unternehmen_fue_auftraege",
    "Umsatzanteil von Produkt-neuheiten": "umsatz_produkt_neuheiten",
    "Umsatzanteil von Markt-neuheiten": "umsatz_markt_neuheiten",
    "Umsatzanteil von Nach-ahmer-innovationen": "umsatz_nachahmer_innovationen",
    "Kostensen-kungsanteil durch Prozess-innovationen": "kostensenkung_prozess_innovationen",
}
